#!/usr/bin/env nextflow

include { GENERATE_GENBANK_FILES } from '../../../modules/local/fileparser/generategenbankfiles/main.nf'

workflow fileParser{

    take:
    ch_input

    main:
    // Check if ch_input contains a directory of files rather than one file, or if it contains a comma-separated list
    if (params.input.contains(',')) {
        input_paths = params.input.split(',').collect{it.trim()}
    } else {
        input_paths = [ params.input ]
    }

    ch_input = Channel.from(input_paths).map { f -> file(f) }
    
    ch_files = ch_input.flatMap { f ->
        if (f.isDirectory()) {
            f.listFiles().collect{ file(it) }
        } else {
            return [ f ]
        }
    }

    // Check file types and split them into channels
    ch_filetype = ch_files.map { f ->
        def filename = f.name
        def baseName = f.baseName
        def type = 'unknown'

        if (filename.endsWith('.fasta') || filename.endsWith('.fa') || filename.endsWith('.fna')) {
            type = 'fasta'

        } else if (filename.endsWith('.gbff')) {
            type = 'gbff'

        } else if (filename.endsWith('.gbk')) {
            type = 'gbk'

        } else if (filename.endsWith('.gff3') || filename.endsWith('.gff')) {
            type = 'gff'

        } else if (filename.endsWith('.faa')) {
            type = 'faa'

        } else if (filename.endsWith('.ffn')) {
            type = 'ffn'

        } else {
            type = 'unknown'

        }

        tuple(f, type)
    }

    // Split channel by filetype
    ch_fasta   = ch_filetype
                    .filter { f, type -> type == "fasta" }
                    .map { f, __ -> f }
    ch_gbk     = ch_filetype
                    .filter { f, type -> type == "gbk" }
                    .map { f, __ -> f }
    ch_gbff    = ch_filetype
                    .filter { f, type -> type == "gbff" }
                    .map { f, __ -> f }
    ch_gff     = ch_filetype
                    .filter { f, type -> type == "gff" }
                    .map { f, __ -> f }
    ch_ffn     = ch_filetype
                    .filter { f, type -> type == "ffn" }
                    .map { f, __ -> f }

    // Remove gff/gbff files if they are missing a sequence
    checked_gffs = CHECK_GFF(ch_gbff.mix(ch_gff))
    ch_complete_gffs = checked_gffs.checked
                            .map{ f, state_file -> 
                            def state = state_file.readLines()[0].trim().toBoolean()
                            if(state) {
                                return f
                            } else {
                                log.warn "Seqeunce missing on submitted GFF file: ${f}. Skipping."
                                null
                            }
                        }.filter { it != null }

    // Check if BAKTA has already run on certain files
    ch_all_inputs = Channel.empty()
    ch_all_inputs = ch_all_inputs.mix(ch_fasta, ch_gbk, ch_complete_gffs, ch_ffn).map{ f -> tuple([id: f.baseName, single_end: false], f)}

    if (!params.force_bakta_annotation){
        checked_ch  = CHECK_ANNOTATION_STATE(ch_all_inputs)

        ch_to_generate = checked_ch.checked 
                            .map{ f, state_file -> 
                                def state = state_file.readLines()[0].trim().toBoolean()
                                def type = state ? "DNB" : "NB"
                                if (type == "DNB"){
                                    log.warn "File potentially already annotated with Bakta: ${f}. Skipping Bakta annotation for this file. If this is incorrect, please rerun the pipeline with the parameter --force_bakta_annotation"
                                }
                                tuple([id: f.baseName, single_end: false], f, type)
                            }

        generatedfiles      = GENERATE_GENBANK_FILES(ch_to_generate)

        ch_meta_needsbakta  = generatedfiles.fnaB

        ch_meta_gbff = generatedfiles.gbff
        ch_meta_gbk  = generatedfiles.gbk
        ch_meta_genbank = ch_meta_gbff.mix(ch_meta_gbk)

        ch_meta_fasta  = generatedfiles.fna
        ch_meta_faa    = generatedfiles.faa
        ch_meta_ffn    = generatedfiles.ffn
        ch_meta_gff    = generatedfiles.gff
    } else {
        ch_meta_needsbakta = ch_all_inputs
    }

    emit:
    ch_meta_needsbakta // This channel should only contain fa, fna, or fasta files that haven't been annotated by bakta yet
    ch_meta_fasta      // These channels contain the files generated by a genbank file input(Only if it has already been annotated by bakta)
    ch_meta_faa
    ch_meta_ffn
    ch_meta_gff
    ch_meta_genbank

}

process CHECK_ANNOTATION_STATE{
    tag "${meta.id}"
    label 'process_low'

    input:
    tuple val(meta), path(file)

    output:
    tuple path(file), path("isAnnotated.txt"), emit: checked

    script:
    """
    # Check if the file has a line that contains "Bakta"
    if grep -q 'Bakta' ${file}; then
        echo true > isAnnotated.txt
    else
        echo false > isAnnotated.txt
    fi
    """
}

process CHECK_GFF{
    label 'process_low'

    input:
    path(file)

    output:
    tuple path(file), path("state.txt"), emit: checked

    script:
    """
    # Check for GenBank/GBFF sequence
    has_sequence=false
    if grep -q 'ORIGIN' ${file}; then
        has_sequence=true
    fi

    # Check for GFF embedded FASTA
    if grep -q '##FASTA' ${file}; then
        has_sequence=true
    fi

    if [ "\$has_sequence" = true ]; then
        echo true > state.txt
    else
        echo false > state.txt
    fi
    """
}