---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python>=3.3
  - bioconda::bcbio-gff=0.7.1
  - pip
  - pip:
    - biopython==1.86